name: Python Package using Conda

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]
      max-parallel: 3

    steps:
    # Step 1: Check out the repository
    - name: Check out repository
      uses: actions/checkout@v4

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    # Step 3: Install Miniconda and Add Conda to Path
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}

    # Step 4: Cache Conda environment
    - name: Cache Conda packages
      uses: actions/cache@v3
      with:
        path: ~/.conda/envs
        key: ${{ runner.os }}-conda-${{ hashFiles('environment.yml') }}
        restore-keys: ${{ runner.os }}-conda

    # Step 5: Create and activate Conda environment
    - name: Create and activate Conda environment
      run: |
        conda env create --file environment.yml --name myenv || conda env update --file environment.yml --name myenv
        echo "conda activate myenv" >> $GITHUB_ENV

    # Step 6: Lint with flake8
    - name: Lint with flake8
      run: |
        conda run -n myenv flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        conda run -n myenv flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    # Step 7: Run tests with pytest
    - name: Test with pytest
      run: |
        conda run -n myenv pytest
#This is the improved version of it
